### ISSUE TITLE
画面右半分の調整

### ISSUE THREAD

**Issue by mzdkzk** [mzdkzk/diexercise#5]
## 概要
ルーム画面(`/rooms/[roomId]`)のデザインの全体的な調整をしたので、右半分(上に表示される注釈語、下に表示される注釈文)のスタイルを調整してほしい

## やること
- [x] 注釈語のデザイン調整
- [x] 注釈語下のGoogle検索リンクのデザイン調整
- [x] 注釈文のデザイン調整
- [x] 注釈文の画面外に出た文章をスクロール出来るように

## 備考
画面右の実装とコンポーネント対応表
* 枠組
  * `app/src/pages/rooms/[roomId].tsx`の`RightTopBox`と`RightBottomBox`
* 配置と注釈語
  * `app/src/pages/rooms/[roomId].tsx`の`GridContainer`下
* 注釈文
  * `app/src/components/Reference.tsx`

**Comment by yamaso** [comment]
注釈枠組みのデザイン調整しました。

**Comment by mzdkzk** [comment]
了解。変更した画面が分かるスクショ付きでプルリクお願いします @yamaso

**Comment by yamaso** [comment]
メモ：Dockerじゃない場合のローカル実行環境
'''
cd app && yarn && yarn dev

**Comment by mzdkzk** [comment]
issueはメモ帳じゃないしDockerは入れよう(windowsでしか起きないエラーとかまで面倒見れない) @yamaso

**Comment by yamaso** [comment]
一時避難やん。
Dockerについては了解。

てかmacだったっけ？ @mzdkzk

**Comment by mzdkzk** [comment]
issueはチャットルームじゃないし僕の端末はWindows
DockerはLinuxで動作するからWindows特有の問題が起きない @yamaso

**Comment by mzdkzk** [comment]
全部終わったっぽいのでクローズ
